name: Build and Release Plugin

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (optional, defaults to latest)'
        required: false
        type: string

jobs:
  build:
    name: Build Plugin Zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get plugin version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION=${{ github.event.release.tag_name }}
          elif [ "${{ inputs.tag }}" != "" ]; then
            VERSION=${{ inputs.tag }}
          else
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
          fi
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION#v}"

      - name: Create plugin zip
        run: |
          # Create plugin directory
          mkdir -p /tmp/plugin-build/breez-woocommerce
          
          # Copy only the files needed for WordPress plugin
          cp breez-woocommerce.php /tmp/plugin-build/breez-woocommerce/
          cp class-wc-gateway-breez.php /tmp/plugin-build/breez-woocommerce/
          cp -r includes/ /tmp/plugin-build/breez-woocommerce/
          cp -r assets/ /tmp/plugin-build/breez-woocommerce/
          cp -r templates/ /tmp/plugin-build/breez-woocommerce/
          
          # Create the zip file
          cd /tmp/plugin-build
          zip -r breez-woocommerce.zip breez-woocommerce/
          
          # Move zip to workspace
          mv breez-woocommerce.zip $GITHUB_WORKSPACE/
          
          # Show what files are included in the zip
          echo "Files included in the plugin zip:"
          unzip -l $GITHUB_WORKSPACE/breez-woocommerce.zip

      - name: Upload zip as release asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./breez-woocommerce.zip
          asset_name: breez-woocommerce-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload zip as workflow artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: breez-woocommerce-${{ steps.get_version.outputs.version }}
          path: ./breez-woocommerce.zip