name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        wp-versions: ['latest']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, mysqli
          tools: composer:v2, wp-cli
          coverage: xdebug
          
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install WP Test Environment
        run: |
          chmod +x tests/bin/install-wp-tests.sh
          tests/bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp-versions }} true
          
      - name: Install WooCommerce for testing
        run: |
          cd $GITHUB_WORKSPACE/tmp/wordpress
          wp core install --url=example.org --title=Example --admin_user=admin --admin_password=password --admin_email=admin@example.org --skip-email
          wp plugin install woocommerce --activate
          cd $GITHUB_WORKSPACE

      - name: Run test suite
        run: composer test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml 